#ifndef VERSION_H
#define VERSION_H

#define VERSION_MAJOR   1
#define VERSION_MINOR   0
#define VERSION_PATCH   0
#define VERSION_RC      VERSION_MAJOR,VERSION_MINOR,VERSION_PATCH,0

#define TO_STRING(s)    #s
#define STRINGIFY(s)    TO_STRING(s)

#define EDITOR_NAME     "PopSoundEditor"
#define EDITOR_VERSION  STRINGIFY(VERSION_MAJOR) "." STRINGIFY(VERSION_MINOR) "." STRINGIFY(VERSION_PATCH)

#endif // VERSION_H
